### ISSUE TITLE
segmentation error with atmos file from RADYN

### ISSUE THREAD

**Issue by pjorion** [ITA-Solar/rh#38]
I get an output model atmos file from fchroma solar model database. I run it through the idl procedures to write it into ncdf file compatible with RH1.5. The parameters in the atmos file look completely fine when I plot them. But RH1.5 throws segmentation errors which do not provide much information about the problem. Attached are the input files for RH1.5 (https://drive.google.com/drive/folders/16npc6d-LC44NSvQDu-WHeCNd6w85kR28?usp=share_link) 
**The error I receive is :**
bnode034:2016153:0:2016153] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10500000104)
[bnode034:2016154:0:2016154] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10500000104)
==== backtrace (tid:2016153) ====
 0 0x0000000000054db0 __GI___sigaction()  :0
 1 0x00000000004098dc distribute_jobs()  ???:0
 2 0x0000000000404a60 main()  ???:0
 3 0x000000000003feb0 __libc_start_call_main()  ???:0
 4 0x000000000003ff60 __libc_start_main_alias_2()  :0
 5 0x0000000000404be5 _start()  ???:0
=================================
[bnode034:2016153] *** Process received signal ***
[bnode034:2016153] Signal: Segmentation fault (11)
[bnode034:2016153] Signal code:  (-6)
[bnode034:2016153] Failing at address: 0x1d65c001ec399
[bnode034:2016153] [ 0] /lib64/libc.so.6(+0x54db0)[0x7f339c654db0]
[bnode034:2016153] [ 1] ./rh15d_ray_pool[0x4098dc]
[bnode034:2016153] [ 2] ./rh15d_ray_pool[0x404a60]
[bnode034:2016153] [ 3] /lib64/libc.so.6(+0x3feb0)[0x7f339c63feb0]
==== backtrace (tid:2016154) ====
 0 0x0000000000054db0 __GI___sigaction()  :0
 1 0x00000000004098dc distribute_jobs()  ???:0
[bnode034:2016153]  2 0x0000000000404a60 main()  ???:0
 3 0x000000000003feb0 __libc_start_call_main()  ???:0
 4 0x000000000003ff60 __libc_start_main_alias_2()  :0
 5 0x0000000000404be5 _start()  ???:0
=================================
[bnode034:2016154] *** Process received signal ***
[bnode034:2016154] Signal: Segmentation fault (11)
[bnode034:2016154] Signal code:  (-6)
[bnode034:2016154] Failing at address: 0x1d65c001ec39a
[ 4] [bnode034:2016154] /lib64/libc.so.6(__libc_start_main+0x80)[0x7f339c63ff60]
[bnode034:2016153] [ 5] ./rh15d_ray_pool[0x404be5]
[bnode034:2016153] *** End of error message ***
[ 0] /lib64/libc.so.6(+0x54db0)[0x7fbe0e854db0]
[bnode034:2016154] [ 1] ./rh15d_ray_pool[0x4098dc]
[bnode034:2016154] [ 2] ./rh15d_ray_pool[0x404a60]
[bnode034:2016154] [ 3] /lib64/libc.so.6(+0x3feb0)[0x7fbe0e83feb0]
[bnode034:2016154] [ 4] /lib64/libc.so.6(__libc_start_main+0x80)[0x7fbe0e83ff60]
[bnode034:2016154] [ 5] ./rh15d_ray_pool[0x404be5]
[bnode034:2016154] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 2016154 on node bnode034 exited on signal 11 (Segmentation fault).

**Comment by tiagopereira** [comment]
Hi, please don't write in large (header) font, it makes it hard to read. RH1.5D is provided "as is", as I don't have time to provide user support. There are few details provided, which makes it hard to identify a bug in RH. I am closing this for now, but if you have more specific details on why this could be a bug in RH, feel free to reopen.
