### ISSUE TITLE
Regarding Molecule treatment

### ISSUE THREAD

**Issue by Astro-Falcon** [ITA-Solar/rh#39]
The code works well for the Atomic line synthesis but when you switch on a molecular line such as the CH molecule, the following warning is shown, there is something that I am unable to implement which is present in the rh code files for the below error.

![rhcode](https://github.com/user-attachments/assets/c5d7e322-1eaf-4a9e-bb81-db32f478f988)

I only changed the line data location in the CH.molecule file in the Molecules_example folder, but I am unsure how to tackle the issue presented in the screenshot attached.

**Comment by tiagopereira** [comment]
Molecules in NLTE were not implemented in RH 1.5D. Could you try to see if it works on [Han's version](https://github.com/han-uitenbroek/rh)? If so, then it may be easier to see how to add them.

**Comment by Astro-Falcon** [comment]
I understood the previous issue and am able to understand more clearly how to toggle the NLTE and LTE treatment for the species.
We need a **collisions.c (similar to h2collisions.c, cocollisions.c) file for implementing the NLTE conditions for the molecules.

Now I just have one more doubt, is it possible for the code to output the LTE populations for the PASSIVE species in the list?
